runtime: php
env: flex

runtime_config:
  document_root: public
  env_variables:
  APP_NAME:CryptoExchange
  APP_ENV:production
  APP_REDIRECT_HTTPS:false
  APP_KEY:base64:JFE1adrUJ+/6eq7qEuOeTNjw7cZvEnzg5UaL2RS7kf4:
  APP_DEBUG:false
  APP_TIMEZONE:UTC
  APP_LOCALE:en
  APP_URL:http://cryptexex.herokuapp.com
  DB_CONNECTION:mysql
  DB_HOST:remotemysql.com
  DB_PORT:3306
  DB_DATABASE:cTUVPTksMJ
  DB_USERNAME:cTUVPTksMJ
  DB_PASSWORD:JXACCKBLQb